version: '3.8'

services:
  frontend:
    image: qiangovo/sweg-frontend:1.0
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    image: qiangovo/sweg-backend:1.0
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: always
